import { describe, it, expect } from 'vitest';
import { BSplineSurfaceFit } from '../src/BSplineSurfaceFit';
import { Vector } from '../src/Vector';

function makeRandom(seed: number): () => number {
    let state = seed >>> 0;
    return () => {
        state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
        return state / 4294967296;
    };
}

function vec3(x: number, y: number, z: number): Vector {
    const v = new Vector(3);
    v.values[0] = x;
    v.values[1] = y;
    v.values[2] = z;
    return v;
}

// A row-major lattice of samples, sample[j0 + numSamples0*j1], generated by
// 'f' evaluated at the uniform parameters u = j0/(n0-1), v = j1/(n1-1).
function lattice(numSamples0: number, numSamples1: number,
    f: (u: number, v: number) => Vector): Vector[] {
    const data: Vector[] = [];
    for (let j1 = 0; j1 < numSamples1; ++j1) {
        for (let j0 = 0; j0 < numSamples0; ++j0) {
            data.push(f(j0 / (numSamples0 - 1), j1 / (numSamples1 - 1)));
        }
    }
    return data;
}

describe('BSplineSurfaceFit construction', () => {
    it('validates its preconditions', () => {
        const data = lattice(10, 10, (u, v) => vec3(u, v, 0));
        // 1 <= degree && degree + 1 < numControls
        expect(() => new BSplineSurfaceFit(0, 6, 10, 3, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 4, 10, 3, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 0, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 4, 10, data)).toThrow();
        // numControls <= numSamples
        expect(() => new BSplineSurfaceFit(3, 12, 10, 3, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 12, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, [])).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, data)).not.toThrow();
    });

    it('reports the input and output information', () => {
        const data = lattice(12, 9, (u, v) => vec3(u, v, u * v));
        const fit = new BSplineSurfaceFit(3, 7, 12, 2, 5, 9, data);
        expect(fit.getNumSamples(0)).toBe(12);
        expect(fit.getNumSamples(1)).toBe(9);
        expect(fit.getDegree(0)).toBe(3);
        expect(fit.getDegree(1)).toBe(2);
        expect(fit.getNumControls(0)).toBe(7);
        expect(fit.getNumControls(1)).toBe(5);
        expect(fit.getSampleData()).toBe(data);
        expect(fit.getControlData().length).toBe(35);
        for (let dim = 0; dim < 2; ++dim) {
            const basis = fit.getBasis(dim);
            expect(basis.isOpen()).toBe(true);
            expect(basis.isUniform()).toBe(true);
            expect(basis.getMinDomain()).toBe(0);
            expect(basis.getMaxDomain()).toBe(1);
        }
        expect(fit.getBasis(0).getDegree()).toBe(3);
        expect(fit.getBasis(1).getDegree()).toBe(2);
    });
});

describe('BSplineSurfaceFit fitting', () => {
    it('recovers constant data exactly', () => {
        const p = vec3(1, -2, 3.5);
        const data = lattice(10, 8, () => p.clone());
        const fit = new BSplineSurfaceFit(3, 6, 10, 3, 5, 8, data);
        for (const control of fit.getControlData()) {
            for (let k = 0; k < 3; ++k) {
                expect(control.values[k]).toBeCloseTo(p.values[k], 9);
            }
        }
        for (const [u, v] of [[0, 0], [0.5, 0.5], [1, 1], [0.3, 0.8]]) {
            const position = fit.getPosition(u, v);
            for (let k = 0; k < 3; ++k) {
                expect(position.values[k]).toBeCloseTo(p.values[k], 9);
            }
        }
    });

    it('recovers a bilinear surface, which lies in the spline space', () => {
        const f = (u: number, v: number): Vector =>
            vec3(2 * u - 1, 3 * v + 1, 1 + 2 * u - v + 4 * u * v);
        const data = lattice(14, 12, f);
        const fit = new BSplineSurfaceFit(3, 8, 14, 3, 7, 12, data);
        for (const [u, v] of [[0, 0], [1, 0], [0, 1], [1, 1],
            [0.25, 0.6], [0.5, 0.5], [0.9, 0.1]]) {
            const position = fit.getPosition(u, v);
            const expected = f(u, v);
            for (let k = 0; k < 3; ++k) {
                expect(position.values[k]).toBeCloseTo(expected.values[k], 7);
            }
        }
    });

    it('recovers a bicubic polynomial surface', () => {
        const f = (u: number, v: number): Vector => vec3(
            u, v, u * u * u - 2 * u * v + v * v * v + 0.5);
        const data = lattice(20, 18, f);
        const fit = new BSplineSurfaceFit(3, 10, 20, 3, 9, 18, data);
        for (const [u, v] of [[0.1, 0.2], [0.4, 0.7], [0.55, 0.35], [0.85, 0.95]]) {
            const position = fit.getPosition(u, v);
            const expected = f(u, v);
            for (let k = 0; k < 3; ++k) {
                expect(position.values[k]).toBeCloseTo(expected.values[k], 6);
            }
        }
    });

    it('interpolates the corner samples of a bilinear surface', () => {
        const f = (u: number, v: number): Vector => vec3(u, v, u + v);
        const data = lattice(10, 10, f);
        const fit = new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, data);
        // An open spline surface passes through its corner control points.
        const controls = fit.getControlData();
        const corner00 = fit.getPosition(0, 0);
        for (let k = 0; k < 3; ++k) {
            expect(corner00.values[k]).toBeCloseTo(controls[0].values[k], 12);
            expect(corner00.values[k]).toBeCloseTo(data[0].values[k], 7);
        }
        const corner11 = fit.getPosition(1, 1);
        for (let k = 0; k < 3; ++k) {
            expect(corner11.values[k]).toBeCloseTo(data[99].values[k], 7);
        }
    });

    it('smooths noisy samples of a smooth surface', () => {
        const rand = makeRandom(2718);
        const truth = (u: number, v: number): number =>
            Math.sin(3 * u) * Math.cos(2 * v);
        const n0 = 30, n1 = 26;
        const data: Vector[] = [];
        for (let j1 = 0; j1 < n1; ++j1) {
            for (let j0 = 0; j0 < n0; ++j0) {
                const u = j0 / (n0 - 1), v = j1 / (n1 - 1);
                data.push(vec3(u, v, truth(u, v) + 0.01 * (2 * rand() - 1)));
            }
        }
        const fit = new BSplineSurfaceFit(3, 10, n0, 3, 9, n1, data);

        let maxError = 0;
        for (const [u, v] of [[0.2, 0.3], [0.5, 0.5], [0.7, 0.25], [0.4, 0.8]]) {
            const position = fit.getPosition(u, v);
            maxError = Math.max(maxError, Math.abs(position.values[2] - truth(u, v)));
        }
        expect(maxError).toBeLessThan(0.01);
    });

    it('clamps parameters outside [0,1]', () => {
        const data = lattice(10, 10, (u, v) => vec3(u, v, u * v));
        const fit = new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, data);
        expect(fit.getPosition(-2, -2).values).toEqual(fit.getPosition(0, 0).values);
        expect(fit.getPosition(3, 3).values).toEqual(fit.getPosition(1, 1).values);
    });
});
