import { describe, it, expect } from 'vitest';
import { check, fc, finite, expectClose, expectVectorClose, seededRandom } from './helpers/arbitraries.js';
import { BSplineSurfaceFit } from '../src/BSplineSurfaceFit.js';
import { BSplineSurface } from '../src/BSplineSurface.js';
import { BSplineCurveFit } from '../src/BSplineCurveFit.js';
import { BasisFunctionInput } from '../src/BasisFunction.js';
import { Vector } from '../src/Vector.js';

function makeRandom(seed: number): () => number {
    let state = seed >>> 0;
    return () => {
        state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
        return state / 4294967296;
    };
}

function vec3(x: number, y: number, z: number): Vector {
    const v = new Vector(3);
    v.values[0] = x;
    v.values[1] = y;
    v.values[2] = z;
    return v;
}

// A row-major lattice of samples, sample[j0 + numSamples0*j1], generated by
// 'f' evaluated at the uniform parameters u = j0/(n0-1), v = j1/(n1-1).
function lattice(numSamples0: number, numSamples1: number,
    f: (u: number, v: number) => Vector): Vector[] {
    const data: Vector[] = [];
    for (let j1 = 0; j1 < numSamples1; ++j1) {
        for (let j0 = 0; j0 < numSamples0; ++j0) {
            data.push(f(j0 / (numSamples0 - 1), j1 / (numSamples1 - 1)));
        }
    }
    return data;
}

describe('BSplineSurfaceFit construction', () => {
    it('validates its preconditions', () => {
        const data = lattice(10, 10, (u, v) => vec3(u, v, 0));
        // 1 <= degree && degree + 1 < numControls
        expect(() => new BSplineSurfaceFit(0, 6, 10, 3, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 4, 10, 3, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 0, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 4, 10, data)).toThrow();
        // numControls <= numSamples
        expect(() => new BSplineSurfaceFit(3, 12, 10, 3, 6, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 12, 10, data)).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, [])).toThrow();
        expect(() => new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, data)).not.toThrow();
    });

    it('reports the input and output information', () => {
        const data = lattice(12, 9, (u, v) => vec3(u, v, u * v));
        const fit = new BSplineSurfaceFit(3, 7, 12, 2, 5, 9, data);
        expect(fit.getNumSamples(0)).toBe(12);
        expect(fit.getNumSamples(1)).toBe(9);
        expect(fit.getDegree(0)).toBe(3);
        expect(fit.getDegree(1)).toBe(2);
        expect(fit.getNumControls(0)).toBe(7);
        expect(fit.getNumControls(1)).toBe(5);
        expect(fit.getSampleData()).toBe(data);
        expect(fit.getControlData().length).toBe(35);
        for (let dim = 0; dim < 2; ++dim) {
            const basis = fit.getBasis(dim);
            expect(basis.isOpen()).toBe(true);
            expect(basis.isUniform()).toBe(true);
            expect(basis.getMinDomain()).toBe(0);
            expect(basis.getMaxDomain()).toBe(1);
        }
        expect(fit.getBasis(0).getDegree()).toBe(3);
        expect(fit.getBasis(1).getDegree()).toBe(2);
    });
});

describe('BSplineSurfaceFit fitting', () => {
    it('recovers constant data exactly', () => {
        const p = vec3(1, -2, 3.5);
        const data = lattice(10, 8, () => p.clone());
        const fit = new BSplineSurfaceFit(3, 6, 10, 3, 5, 8, data);
        for (const control of fit.getControlData()) {
            for (let k = 0; k < 3; ++k) {
                expect(control.values[k]).toBeCloseTo(p.values[k], 9);
            }
        }
        for (const [u, v] of [[0, 0], [0.5, 0.5], [1, 1], [0.3, 0.8]]) {
            const position = fit.getPosition(u, v);
            for (let k = 0; k < 3; ++k) {
                expect(position.values[k]).toBeCloseTo(p.values[k], 9);
            }
        }
    });

    it('recovers a bilinear surface, which lies in the spline space', () => {
        const f = (u: number, v: number): Vector =>
            vec3(2 * u - 1, 3 * v + 1, 1 + 2 * u - v + 4 * u * v);
        const data = lattice(14, 12, f);
        const fit = new BSplineSurfaceFit(3, 8, 14, 3, 7, 12, data);
        for (const [u, v] of [[0, 0], [1, 0], [0, 1], [1, 1],
            [0.25, 0.6], [0.5, 0.5], [0.9, 0.1]]) {
            const position = fit.getPosition(u, v);
            const expected = f(u, v);
            for (let k = 0; k < 3; ++k) {
                expect(position.values[k]).toBeCloseTo(expected.values[k], 7);
            }
        }
    });

    it('recovers a bicubic polynomial surface', () => {
        const f = (u: number, v: number): Vector => vec3(
            u, v, u * u * u - 2 * u * v + v * v * v + 0.5);
        const data = lattice(20, 18, f);
        const fit = new BSplineSurfaceFit(3, 10, 20, 3, 9, 18, data);
        for (const [u, v] of [[0.1, 0.2], [0.4, 0.7], [0.55, 0.35], [0.85, 0.95]]) {
            const position = fit.getPosition(u, v);
            const expected = f(u, v);
            for (let k = 0; k < 3; ++k) {
                expect(position.values[k]).toBeCloseTo(expected.values[k], 6);
            }
        }
    });

    it('interpolates the corner samples of a bilinear surface', () => {
        const f = (u: number, v: number): Vector => vec3(u, v, u + v);
        const data = lattice(10, 10, f);
        const fit = new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, data);
        // An open spline surface passes through its corner control points.
        const controls = fit.getControlData();
        const corner00 = fit.getPosition(0, 0);
        for (let k = 0; k < 3; ++k) {
            expect(corner00.values[k]).toBeCloseTo(controls[0].values[k], 12);
            expect(corner00.values[k]).toBeCloseTo(data[0].values[k], 7);
        }
        const corner11 = fit.getPosition(1, 1);
        for (let k = 0; k < 3; ++k) {
            expect(corner11.values[k]).toBeCloseTo(data[99].values[k], 7);
        }
    });

    it('smooths noisy samples of a smooth surface', () => {
        const rand = makeRandom(2718);
        const truth = (u: number, v: number): number =>
            Math.sin(3 * u) * Math.cos(2 * v);
        const n0 = 30, n1 = 26;
        const data: Vector[] = [];
        for (let j1 = 0; j1 < n1; ++j1) {
            for (let j0 = 0; j0 < n0; ++j0) {
                const u = j0 / (n0 - 1), v = j1 / (n1 - 1);
                data.push(vec3(u, v, truth(u, v) + 0.01 * (2 * rand() - 1)));
            }
        }
        const fit = new BSplineSurfaceFit(3, 10, n0, 3, 9, n1, data);

        let maxError = 0;
        for (const [u, v] of [[0.2, 0.3], [0.5, 0.5], [0.7, 0.25], [0.4, 0.8]]) {
            const position = fit.getPosition(u, v);
            maxError = Math.max(maxError, Math.abs(position.values[2] - truth(u, v)));
        }
        expect(maxError).toBeLessThan(0.01);
    });

    it('clamps parameters outside [0,1]', () => {
        const data = lattice(10, 10, (u, v) => vec3(u, v, u * v));
        const fit = new BSplineSurfaceFit(3, 6, 10, 3, 6, 10, data);
        expect(fit.getPosition(-2, -2).values).toEqual(fit.getPosition(0, 0).values);
        expect(fit.getPosition(3, 3).values).toEqual(fit.getPosition(1, 1).values);
    });
});

// ---------------------------------------------------------------------------
// Verification pass (V05). The fitted surface is cross-checked against the
// separately ported BSplineSurface class, and the tensor-product structure of
// the fit is cross-checked against two independent BSplineCurveFit fits.
// ---------------------------------------------------------------------------
describe('BSplineSurfaceFit verification', () => {
    interface Case {
        d0: number; n0: number; s0: number;
        d1: number; n1: number; s1: number;
        samples: Vector[];
    }

    const caseArb: fc.Arbitrary<Case> = fc.tuple(
        fc.integer({ min: 1, max: 2 }),   // degree0
        fc.integer({ min: 0, max: 2 }),   // numControls0 - degree0 - 2
        fc.integer({ min: 0, max: 4 }),   // numSamples0 - numControls0
        fc.integer({ min: 1, max: 2 }),   // degree1
        fc.integer({ min: 0, max: 2 }),   // numControls1 - degree1 - 2
        fc.integer({ min: 0, max: 4 }),   // numSamples1 - numControls1
        fc.array(finite(-10, 10), { minLength: 3 * 121, maxLength: 3 * 121 })
    ).map(([d0, e0, x0, d1, e1, x1, data]) => {
        const n0 = d0 + 2 + e0;
        const n1 = d1 + 2 + e1;
        const s0 = n0 + x0;
        const s1 = n1 + x1;
        const samples: Vector[] = [];
        for (let i = 0; i < s0 * s1; ++i) {
            const p = new Vector(3);
            for (let k = 0; k < 3; ++k) { p.values[k] = data[(i * 3 + k) % data.length]; }
            samples.push(p);
        }
        return { d0, n0, s0, d1, n1, s1, samples };
    });

    const fitOf = (c: Case): BSplineSurfaceFit =>
        new BSplineSurfaceFit(c.d0, c.n0, c.s0, c.d1, c.n1, c.s1, c.samples);

    /** The fitted surface rebuilt as a BSplineSurface over the same basis. */
    function asSurface(fit: BSplineSurfaceFit): BSplineSurface {
        const input = [
            new BasisFunctionInput(fit.getNumControls(0), fit.getDegree(0)),
            new BasisFunctionInput(fit.getNumControls(1), fit.getDegree(1))
        ];
        return new BSplineSurface(3, input, fit.getControlData());
    }

    it('evaluates the same surface as BSplineSurface over the fitted controls', () => {
        check(fc.tuple(caseArb, finite(0, 1), finite(0, 1)), ([c, u, v]) => {
            const fit = fitOf(c);
            const surface = asSurface(fit);
            expectVectorClose(fit.getPosition(u, v), surface.getPosition(u, v), 1e-9, 1e-10);
            return true;
        }, 50);
    });

    it('reports the sizes implied by its constructor arguments', () => {
        check(caseArb, c => {
            const fit = fitOf(c);
            expect(fit.getDegree(0)).toBe(c.d0);
            expect(fit.getDegree(1)).toBe(c.d1);
            expect(fit.getNumControls(0)).toBe(c.n0);
            expect(fit.getNumControls(1)).toBe(c.n1);
            expect(fit.getNumSamples(0)).toBe(c.s0);
            expect(fit.getNumSamples(1)).toBe(c.s1);
            expect(fit.getControlData().length).toBe(c.n0 * c.n1);
            expect(fit.getSampleData()).toBe(c.samples);
            return true;
        }, 50);
    });

    // Any polynomial of degree <= (degree0, degree1) in (u, v) lies in the
    // tensor-product spline space, so the least-squares fit reproduces it.
    it('reproduces polynomial surfaces that lie in the spline space', () => {
        check(fc.tuple(fc.integer({ min: 1, max: 3 }), fc.integer({ min: 1, max: 3 }),
            fc.array(finite(-3, 3), { minLength: 16, maxLength: 16 }),
            finite(0, 1), finite(0, 1)), ([d0, d1, coeff, u, v]) => {
                const n0 = d0 + 3;
                const n1 = d1 + 3;
                const s0 = n0 + 5;
                const s1 = n1 + 5;
                const poly = (x: number, y: number): number => {
                    let value = 0;
                    for (let a = 0; a <= d0; ++a) {
                        for (let b = 0; b <= d1; ++b) {
                            value += coeff[a * 4 + b] * Math.pow(x, a) * Math.pow(y, b);
                        }
                    }
                    return value;
                };
                const samples: Vector[] = [];
                for (let j1 = 0; j1 < s1; ++j1) {
                    for (let j0 = 0; j0 < s0; ++j0) {
                        const p = new Vector(3);
                        p.values[0] = poly(j0 / (s0 - 1), j1 / (s1 - 1));
                        samples.push(p);
                    }
                }
                const fit = new BSplineSurfaceFit(d0, n0, s0, d1, n1, s1, samples);
                // The two normal-equation solves are mildly ill conditioned.
                expectClose(fit.getPosition(u, v).values[0], poly(u, v), 1e-7, 1e-7);
                return true;
            }, 60);
    });

    // A separable sample lattice P[j0][j1] = f(j0) * g(j1) must produce the
    // separable control lattice Q[i0][i1] = qf[i0] * qg[i1] obtained from two
    // independent one-dimensional least-squares solves. This checks the
    // Q = X0*P*X1^T double summation and its index arithmetic against
    // BSplineCurveFit, up to the end-point override that the curve fit
    // applies and the surface fit does not.
    it('factorises a separable sample lattice like two 1D fits', () => {
        const d = 2, n = 6, s = 14;
        const rand = seededRandom(0x51ab3);
        const f: number[] = [];
        const g: number[] = [];
        for (let i = 0; i < s; ++i) { f.push(2 * rand() - 1); }
        for (let i = 0; i < s; ++i) { g.push(2 * rand() - 1); }

        const samples: Vector[] = [];
        for (let j1 = 0; j1 < s; ++j1) {
            for (let j0 = 0; j0 < s; ++j0) {
                const p = new Vector(3);
                p.values[0] = f[j0] * g[j1];
                samples.push(p);
            }
        }
        const fit = new BSplineSurfaceFit(d, n, s, d, n, s, samples);

        // The 1D solves, with the end-point override undone by reading the
        // interior controls only.
        const fitF = new BSplineCurveFit(1, s, f, d, n);
        const fitG = new BSplineCurveFit(1, s, g, d, n);
        const qf = fitF.getControlData();
        const qg = fitG.getControlData();

        // Interior x interior: the products must agree.
        const controls = fit.getControlData();
        for (let i1 = 1; i1 < n - 1; ++i1) {
            for (let i0 = 1; i0 < n - 1; ++i0) {
                expectClose(controls[i0 + n * i1].values[0], qf[i0] * qg[i1], 1e-8, 1e-8);
            }
        }
    });

    it('rejects inputs that violate the documented preconditions', () => {
        const samples = Array.from({ length: 400 }, () => new Vector(3));
        expect(() => new BSplineSurfaceFit(0, 5, 8, 2, 5, 8, samples)).toThrow(/Invalid degree/);
        expect(() => new BSplineSurfaceFit(2, 3, 8, 2, 5, 8, samples)).toThrow(/Invalid degree/);
        expect(() => new BSplineSurfaceFit(2, 5, 4, 2, 5, 8, samples))
            .toThrow(/Invalid number of controls/);
        expect(() => new BSplineSurfaceFit(2, 5, 8, 0, 5, 8, samples)).toThrow(/Invalid degree/);
        expect(() => new BSplineSurfaceFit(2, 5, 8, 2, 5, 4, samples))
            .toThrow(/Invalid number of controls/);
        expect(() => new BSplineSurfaceFit(2, 5, 8, 2, 5, 8, [new Vector(3)]))
            .toThrow(/Invalid sample data/);
    });

    it('clamps parameters outside the unit square', () => {
        check(fc.tuple(caseArb, finite(1, 4)), ([c, over]) => {
            const fit = fitOf(c);
            expectVectorClose(fit.getPosition(-over, 0.5), fit.getPosition(0, 0.5), 1e-12, 1e-12);
            expectVectorClose(fit.getPosition(1 + over, 0.5), fit.getPosition(1, 0.5), 1e-12, 1e-12);
            expectVectorClose(fit.getPosition(0.5, -over), fit.getPosition(0.5, 0), 1e-12, 1e-12);
            expectVectorClose(fit.getPosition(0.5, 1 + over), fit.getPosition(0.5, 1), 1e-12, 1e-12);
            return true;
        }, 40);
    });
});
