// C++ oracle driver. See ORACLE.md.
//
//   node scripts/oracle.mjs build [glob]        compile oracle/build/oracle.exe (Windows + MSVC)
//   node scripts/oracle.mjs gen [filter]        regenerate committed goldens (20 records per case)
//   node scripts/oracle.mjs deep [n] [filter]   n records per case into oracle/out/deep, then replay
//   node scripts/oracle.mjs report              replay committed goldens and write docs/ORACLE-REPORT.md
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const exe = join(root, 'oracle', 'build', 'oracle.exe');
const GOLDEN_RECORDS = 20;

function run(command, args, options = {}) {
    const result = spawnSync(command, args, { cwd: root, stdio: 'inherit', ...options });
    if (result.status !== 0) { process.exit(result.status ?? 1); }
}

function requireExe() {
    if (!existsSync(exe)) {
        console.error('oracle.exe not built; run: node scripts/oracle.mjs build');
        process.exit(1);
    }
}

function vitest(filter, env) {
    const pattern = filter ? `test/oracle/${filter}` : 'test/oracle';
    const result = spawnSync('npx', ['vitest', 'run', pattern], {
        cwd: root, stdio: 'inherit', shell: true, env: { ...process.env, ...env }
    });
    return result.status ?? 1;
}

const [command, ...args] = process.argv.slice(2);
switch (command) {
    case 'build':
        run('cmd', ['/c', join('oracle', 'build.cmd'), ...(args[0] ? [args[0]] : [])]);
        break;

    case 'gen':
        requireExe();
        run(exe, ['--out', join(root, 'oracle', 'golden'), '--n', String(GOLDEN_RECORDS),
            ...(args[0] ? ['--filter', args[0]] : [])]);
        break;

    case 'deep': {
        requireExe();
        const n = args[0] ?? '2000';
        const out = join(root, 'oracle', 'out', 'deep');
        rmSync(out, { recursive: true, force: true });
        mkdirSync(out, { recursive: true });
        run(exe, ['--out', out, '--n', n, ...(args[1] ? ['--filter', args[1]] : [])]);
        // Families absent from a filtered deep run fall back to nothing, so
        // replay only the families that were generated.
        let status = 0;
        for (const file of readdirSync(out)) {
            const family = file.replace(/\.txt$/, '');
            status |= vitest(`${family}.oracle.test.ts`, { ORACLE_GOLDEN_DIR: out });
        }
        process.exit(status);
        break;
    }

    case 'report': {
        const statsDir = join(root, 'oracle', 'out', 'stats');
        rmSync(statsDir, { recursive: true, force: true });
        const status = vitest(undefined, { ORACLE_STATS: '1' });
        const families = readdirSync(statsDir).filter((f) => f.endsWith('.json')).sort()
            .map((f) => JSON.parse(readFileSync(join(statsDir, f), 'utf8')));
        const lines = [];
        let cases = 0, records = 0, reals = 0, exact = 0, skipped = 0, exactCases = 0;
        const rows = [], skips = [], deviations = [];
        let deviating = 0;
        for (const fam of families) {
            let fc = 0, fr = 0, fo = 0, fe = 0, fx = 0, worst = 0, worstCase = '';
            for (const [name, s] of Object.entries(fam.cases)) {
                ++fc;
                if (s.skipped !== undefined) {
                    ++skipped;
                    skips.push(`| ${fam.family} | \`${name}\` | ${s.skipped} |`);
                    continue;
                }
                if (s.deviation !== undefined) {
                    ++deviating;
                    deviations.push(`| ${fam.family} | \`${name}\` | ${s.deviatingRecords} of `
                        + `${s.records} | ${s.deviation} |`);
                    continue;
                }
                fr += s.records; fo += s.realOutputs; fe += s.exactOutputs;
                if (s.realOutputs === s.exactOutputs) { ++fx; }
                if (s.maxRelErr > worst) { worst = s.maxRelErr; worstCase = name; }
            }
            cases += fc; records += fr; reals += fo; exact += fe; exactCases += fx;
            rows.push(`| ${fam.family} | ${fc} | ${fr} | ${fo} | `
                + `${fo ? (100 * fe / fo).toFixed(2) : '100.00'}% | ${fx} | `
                + `${worst === 0 ? '0' : worst.toExponential(2)} | ${worstCase ? `\`${worstCase}\`` : ''} |`);
        }
        const header = families[0]?.header ?? [];
        lines.push('# C++ oracle agreement report', '',
            'Generated by `npm run oracle:report` from the committed goldens in `oracle/golden`.',
            'Each golden record holds inputs generated by the C++ harness and the outputs of the',
            'upstream GTE code compiled with MSVC; the port replays the same inputs. See',
            '[ORACLE.md](../ORACLE.md).', '',
            ...header.slice(1).map((h) => `- ${h.substring(2)}`), '',
            `**${cases} cases, ${records} records, ${reals} floating-point outputs compared; `
            + `${reals ? (100 * exact / reals).toFixed(2) : '100.00'}% bit-identical to the C++ build. `
            + `${exactCases} cases are bit-identical on every output. ${deviating} further cases `
            + `demonstrate deliberate fixes of upstream defects and ${skipped} are skipped.**`, '',
            'Discrete outputs (booleans, counts, indices) always compare exactly and are not counted',
            'in the floating-point columns. "max scaled error" is `|port - C++| / max(1, |port|, |C++|)`.', '',
            '| family | cases | records | real outputs | bit-identical | fully exact cases | max scaled error | worst case |',
            '| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |',
            ...rows, '');
        if (skips.length > 0) {
            lines.push('## Skipped cases', '',
                '| family | case | reason |', '| --- | --- | --- |', ...skips, '');
        }
        if (deviations.length > 0) {
            lines.splice(lines.length, 0, '## Deliberate deviations from the C++ build', '',
                'These cases feed the port inputs on which upstream is defective. The port is',
                'expected to disagree with the C++ output; the test fails if it ever agrees on',
                'every record.', '',
                '| family | case | disagreeing records | record of the decision |',
                '| --- | --- | ---: | --- |', ...deviations, '');
        }
        writeFileSync(join(root, 'docs', 'ORACLE-REPORT.md'), lines.join('\n'));
        console.log('wrote docs/ORACLE-REPORT.md');
        process.exit(status);
        break;
    }

    default:
        console.error('usage: node scripts/oracle.mjs build|gen|deep|report');
        process.exit(2);
}
