// gtengine-js: TypeScript port of Geometric Tools Engine (GTE) Integration.h
// Upstream: David Eberly, Geometric Tools, Redmond WA 98052
// Copyright (c) 1998-2026 David Eberly
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

import { RootsPolynomial } from './RootsPolynomial.js';

// Numerical integration: the trapezoid rule, Romberg integration
// (trapezoid rule plus Richardson extrapolation) and Gauss-Legendre
// quadrature.
//
// Port notes:
// - 'std::function<Real(Real)>' becomes '(t: number) => number'.
// - ComputeQuadratureInfo writes its two outputs through reference
//   parameters; the port returns them as { roots, coefficients }.
// - Upstream resizes 'roots' to 'degree' and then calls
//   RootsPolynomial::Find, which may report fewer roots than 'degree'; the
//   trailing entries then keep their value-initialized zeros. The port
//   reproduces that exactly (a zero-filled array of length 'degree' into
//   which the roots found are copied), so degenerate cases behave the same.
export class Integration {
    // A simple algorithm, but slow to converge as the number of samples is
    // increased. The 'numSamples' needs to be two or larger.
    static trapezoidRule(numSamples: number, a: number, b: number,
        integrand: (t: number) => number): number {
        const h = (b - a) / (numSamples - 1);
        let result = 0.5 * (integrand(a) + integrand(b));
        for (let i = 1; i <= numSamples - 2; ++i) {
            result += integrand(a + i * h);
        }
        result *= h;
        return result;
    }

    // The trapezoid rule is used to generate initial estimates, but then
    // Richardson extrapolation is used to improve the estimates. This is
    // preferred over trapezoidRule. The 'order' must be positive.
    static romberg(order: number, a: number, b: number,
        integrand: (t: number) => number): number {
        const half = 0.5;
        const rom: number[][] = [];
        for (let i = 0; i < order; ++i) {
            rom.push([0, 0]);
        }

        let h = b - a;
        rom[0][0] = half * h * (integrand(a) + integrand(b));
        for (let i0 = 2, p0 = 1; i0 <= order; ++i0, p0 *= 2, h *= half) {
            // Approximations via the trapezoid rule.
            let sum = 0;
            let i1: number;
            for (i1 = 1; i1 <= p0; ++i1) {
                sum += integrand(a + h * (i1 - half));
            }

            // Richardson extrapolation.
            rom[0][1] = half * (rom[0][0] + h * sum);
            for (let i2 = 1, i2m1 = 0, p2 = 4; i2 < i0; ++i2, ++i2m1, p2 *= 4) {
                rom[i2][1] = (p2 * rom[i2m1][1] - rom[i2m1][0]) / (p2 - 1);
            }

            for (i1 = 0; i1 < i0; ++i1) {
                rom[i1][0] = rom[i1][1];
            }
        }

        return rom[order - 1][0];
    }

    // Gaussian quadrature estimates the integral of a function f(x) defined
    // on [-1,1] using
    //   integral_{-1}^{1} f(t) dt = sum_{i=0}^{n-1} c[i]*f(r[i])
    // where r[i] are the roots of the Legendre polynomial p(t) of degree n
    // and
    //   c[i] = integral_{-1}^{1} prod_{j=0,j!=i} (t-r[j])/(r[i]-r[j]) dt
    // To integrate over [a,b], a transformation to [-1,1] is applied
    // internally: x = ((b-a)*t + (b+a))/2. The Legendre polynomials are
    // generated by
    //   P[0](x) = 1, P[1](x) = x,
    //   P[k](x) = ((2*k-1)*x*P[k-1](x) - (k-1)*P[k-2](x))/k, k >= 2
    // Implementing the polynomial generation is simple, and computing the
    // roots requires a numerical method for finding polynomial roots. The
    // challenging task is to develop an efficient algorithm for computing
    // the coefficients c[i] for a specified degree. The 'degree' must be two
    // or larger.
    static computeQuadratureInfo(degree: number):
        { roots: number[]; coefficients: number[] } {
        const zero = 0;
        const one = 1;
        const half = 0.5;

        const poly: number[][] = [];
        for (let i = 0; i <= degree; ++i) {
            poly.push([]);
        }

        poly[0] = [one];
        poly[1] = [zero, one];

        for (let n = 2, nm1 = 1, nm2 = 0, np1 = 3; n <= degree;
            ++n, ++nm1, ++nm2, ++np1) {
            const mult0 = nm1 / n;
            const mult1 = (2 * n - 1) / n;

            poly[n] = new Array<number>(np1).fill(0);
            poly[n][0] = -mult0 * poly[nm2][0];
            for (let i = 1, im1 = 0; i <= nm2; ++i, ++im1) {
                poly[n][i] = mult1 * poly[nm1][im1] - mult0 * poly[nm2][i];
            }
            poly[n][nm1] = mult1 * poly[nm1][nm2];
            poly[n][n] = mult1 * poly[nm1][nm1];
        }

        // Upstream sizes 'roots' to 'degree' before the call, so entries not
        // written by Find remain zero.
        const roots = new Array<number>(degree).fill(0);
        const found = RootsPolynomial.find(degree, poly[degree], 2048);
        for (let i = 0; i < found.length && i < degree; ++i) {
            roots[i] = found[i];
        }

        const coefficients = new Array<number>(roots.length).fill(0);
        const n = roots.length - 1;
        const subroots = new Array<number>(n).fill(0);
        for (let i = 0; i < roots.length; ++i) {
            let denominator = 1;
            for (let j = 0, k = 0; j < roots.length; ++j) {
                if (j !== i) {
                    subroots[k++] = roots[j];
                    denominator *= roots[i] - roots[j];
                }
            }

            const lastSubroot = subroots[n - 1];
            const delta: [number, number] = [
                -one - lastSubroot,
                +one - lastSubroot
            ];

            const weights: [number, number][] = [];
            for (let k = 0; k < n; ++k) {
                weights.push([0, 0]);
            }
            weights[0][0] = half * delta[0] * delta[0];
            weights[0][1] = half * delta[1] * delta[1];
            for (let k = 1; k < n; ++k) {
                const dk = k;
                const mult = -dk / (dk + 2);
                weights[k][0] = mult * delta[0] * weights[k - 1][0];
                weights[k][1] = mult * delta[1] * weights[k - 1][1];
            }

            // info[m] holds the number of set bits of m and the product over
            // the selected subroots of (-1 - r) and (+1 - r).
            const numElements = 1 << (n - 1);
            const infoNumBits = new Array<number>(numElements).fill(0);
            const infoProduct0 = new Array<number>(numElements).fill(0);
            const infoProduct1 = new Array<number>(numElements).fill(0);
            infoNumBits[0] = 0;
            infoProduct0[0] = one;
            infoProduct1[0] = one;
            for (let ipow = 1, r = 0; ipow < numElements; ipow <<= 1, ++r) {
                infoNumBits[ipow] = 1;
                infoProduct0[ipow] = -one - subroots[r];
                infoProduct1[ipow] = +one - subroots[r];
                for (let m = 1, j = ipow + 1; m < ipow; ++m, ++j) {
                    infoNumBits[j] = infoNumBits[m] + 1;
                    infoProduct0[j] = infoProduct0[ipow] * infoProduct0[m];
                    infoProduct1[j] = infoProduct1[ipow] * infoProduct1[m];
                }
            }

            const sum: [number, number][] = [];
            for (let k = 0; k < n; ++k) {
                sum.push([0, 0]);
            }
            for (let k = 0; k < numElements; ++k) {
                sum[infoNumBits[k]][0] += infoProduct0[k];
                sum[infoNumBits[k]][1] += infoProduct1[k];
            }

            const total: [number, number] = [0, 0];
            for (let k = 0; k < n; ++k) {
                total[0] += weights[n - 1 - k][0] * sum[k][0];
                total[1] += weights[n - 1 - k][1] * sum[k][1];
            }

            coefficients[i] = (total[1] - total[0]) / denominator;
        }

        return { roots, coefficients };
    }

    static gaussianQuadrature(roots: readonly number[],
        coefficients: readonly number[], a: number, b: number,
        integrand: (t: number) => number): number {
        const half = 0.5;
        const radius = half * (b - a);
        const center = half * (b + a);
        let result = 0;
        for (let i = 0; i < roots.length; ++i) {
            result += coefficients[i] * integrand(radius * roots[i] + center);
        }
        result *= radius;
        return result;
    }
}
