// gtengine-js: TypeScript port of Geometric Tools Engine (GTE) MassSpringArbitrary.h
// Upstream: David Eberly, Geometric Tools, Redmond WA 98052
// Copyright (c) 1998-2026 David Eberly
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

// A set of M masses connected by S springs of arbitrary topology. The state
// is advanced by the fourth-order Runge-Kutta solver of ParticleSystem.
//
// Port notes:
// - Upstream 'MassSpringArbitrary<N, Real>' becomes a runtime dimension,
//   matching the ParticleSystem port: 'new MassSpringArbitrary(dimension,
//   numParticles, numSprings, step)'.
// - The upstream nested struct 'Spring' is exported as
//   'MassSpringArbitrarySpring' because src/index.ts star-exports every file
//   (the same precedent as 'ParticleSystemTemporary').
// - Upstream 'std::set<int32_t>' adjacency becomes a 'Set<number>'. The
//   iteration order of the springs adjacent to a particle affects only the
//   floating-point summation order of the acceleration; upstream's sorted
//   order is replicated by inserting spring indices in increasing order in
//   the typical usage (setSpring called for index 0, 1, 2, ...), and the
//   membership semantics (no duplicate spring index per particle) match.
// - The class is abstract in name only upstream (Acceleration is implemented
//   here), so the port is a concrete class; derive from it to supply nonzero
//   external forces by overriding externalAcceleration.

import { Vector, add, length as vectorLength, mul, sub } from './Vector';
import { ParticleSystem } from './ParticleSystem';

// The port of MassSpringArbitrary::Spring. A spring connects particle0 and
// particle1, has a spring constant and a resting length.
export class MassSpringArbitrarySpring {
    particle0: number;
    particle1: number;
    constant: number;
    length: number;

    constructor(particle0: number = 0, particle1: number = 0,
        constant: number = 0, length: number = 0) {
        this.particle0 = particle0;
        this.particle1 = particle1;
        this.constant = constant;
        this.length = length;
    }

    clone(): MassSpringArbitrarySpring {
        return new MassSpringArbitrarySpring(this.particle0, this.particle1,
            this.constant, this.length);
    }
}

export class MassSpringArbitrary extends ParticleSystem {
    protected mSpring: MassSpringArbitrarySpring[];

    // Each particle has an associated set of spring indices for those springs
    // adjacent to the particle. The set elements are spring indices, not
    // indices of adjacent particles.
    protected mAdjacent: Set<number>[];

    // Construction. This class represents a set of numParticles masses that
    // are connected by numSprings springs with arbitrary topology. The
    // function setSpring(...) should be called for each spring that you want
    // in the system.
    constructor(dimension: number, numParticles: number, numSprings: number,
        step: number) {
        super(dimension, numParticles, step);
        this.mSpring = new Array<MassSpringArbitrarySpring>(numSprings);
        for (let i = 0; i < numSprings; ++i) {
            this.mSpring[i] = new MassSpringArbitrarySpring();
        }
        this.mAdjacent = new Array<Set<number>>(numParticles);
        for (let i = 0; i < numParticles; ++i) {
            this.mAdjacent[i] = new Set<number>();
        }
    }

    // Member access.
    getNumSprings(): number {
        return this.mSpring.length;
    }

    // C++ assignment copies the spring, so the port clones it; the caller may
    // reuse or modify the input object afterwards.
    setSpring(index: number, spring: MassSpringArbitrarySpring): void {
        this.mSpring[index] = spring.clone();
        this.mAdjacent[spring.particle0].add(index);
        this.mAdjacent[spring.particle1].add(index);
    }

    // Upstream returns a 'Spring const&'. The port returns the live internal
    // object, so it must not be modified by the caller.
    getSpring(index: number): MassSpringArbitrarySpring {
        return this.mSpring[index];
    }

    // The default external force is zero. Derive a class from this one to
    // provide nonzero external forces such as gravity, wind, friction, and so
    // on. This function is called by acceleration(...) to compute the impulse
    // F/m generated by the external force F.
    externalAcceleration(_i: number, _time: number,
        _position: readonly Vector[], _velocity: readonly Vector[]): Vector {
        return Vector.zero(this.mDimension);
    }

    // Callback for acceleration (the ODE solver uses x" = F/m) applied to
    // particle i. The positions and velocities are not necessarily mPosition
    // and mVelocity, because the ODE solver evaluates the impulse function at
    // intermediate positions.
    protected acceleration(i: number, time: number,
        position: readonly Vector[], velocity: readonly Vector[]): Vector {
        // Compute spring forces on position X[i]. The positions are not
        // necessarily mPosition, because the RK4 solver in ParticleSystem
        // evaluates the acceleration function at intermediate positions.

        let acceleration = this.externalAcceleration(i, time, position, velocity);

        for (const adj of this.mAdjacent[i]) {
            // Process a spring connected to particle i.
            const spring = this.mSpring[adj];
            let diff: Vector;
            if (i !== spring.particle0) {
                diff = sub(position[spring.particle0], position[i]);
            }
            else {
                diff = sub(position[spring.particle1], position[i]);
            }

            const ratio = spring.length / vectorLength(diff);
            const force = mul(spring.constant * (1 - ratio), diff);
            acceleration = add(acceleration, mul(this.mInvMass[i], force));
        }

        return acceleration;
    }
}
