// gtengine-js: TypeScript port of Geometric Tools Engine (GTE) MassSpringCurve.h
// Upstream: David Eberly, Geometric Tools, Redmond WA 98052
// Copyright (c) 1998-2026 David Eberly
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

// A set of numParticles-1 springs connecting numParticles masses that lie on
// a curve. The state is advanced by the fourth-order Runge-Kutta solver of
// ParticleSystem.
//
// Port notes:
// - Upstream 'MassSpringCurve<N, Real>' becomes a runtime dimension, matching
//   the ParticleSystem port: 'new MassSpringCurve(dimension, numParticles,
//   step)'.
// - The class is abstract in name only upstream (Acceleration is implemented
//   here), so the port is a concrete class; derive from it to supply nonzero
//   external forces by overriding externalAcceleration.

import { Vector, add, length as vectorLength, mul, sub } from './Vector.js';
import { ParticleSystem } from './ParticleSystem.js';

export class MassSpringCurve extends ParticleSystem {
    // The spring constants and the spring resting lengths, one per spring.
    protected mConstant: number[];
    protected mLength: number[];

    // Construction. This class represents a set of numParticles-1 springs
    // connecting numParticles masses that lie on a curve.
    constructor(dimension: number, numParticles: number, step: number) {
        super(dimension, numParticles, step);
        this.mConstant = new Array<number>(numParticles - 1).fill(0);
        this.mLength = new Array<number>(numParticles - 1).fill(0);
    }

    // Member access. The parameters are spring constant and spring resting
    // length.
    getNumSprings(): number {
        return this.mNumParticles - 1;
    }

    setConstant(i: number, constant: number): void {
        this.mConstant[i] = constant;
    }

    setLength(i: number, length: number): void {
        this.mLength[i] = length;
    }

    getConstant(i: number): number {
        return this.mConstant[i];
    }

    getLength(i: number): number {
        return this.mLength[i];
    }

    // The default external force is zero. Derive a class from this one to
    // provide nonzero external forces such as gravity, wind, friction, and so
    // on. This function is called by acceleration(...) to compute the impulse
    // F/m generated by the external force F.
    externalAcceleration(_i: number, _time: number,
        _position: readonly Vector[], _velocity: readonly Vector[]): Vector {
        return Vector.zero(this.mDimension);
    }

    // Callback for acceleration (the ODE solver uses x" = F/m) applied to
    // particle i. The positions and velocities are not necessarily mPosition
    // and mVelocity, because the ODE solver evaluates the impulse function at
    // intermediate positions.
    protected acceleration(i: number, time: number,
        position: readonly Vector[], velocity: readonly Vector[]): Vector {
        // Compute spring forces on position X[i]. The positions are not
        // necessarily mPosition, because the RK4 solver in ParticleSystem
        // evaluates the acceleration function at intermediate positions. The
        // endpoints of the curve of masses must be handled separately,
        // because each has only one spring attached to it.

        let acceleration = this.externalAcceleration(i, time, position, velocity);
        let diff: Vector, force: Vector, ratio: number;

        if (i > 0) {
            const iM1 = i - 1;
            diff = sub(position[iM1], position[i]);
            ratio = this.mLength[iM1] / vectorLength(diff);
            force = mul(this.mConstant[iM1] * (1 - ratio), diff);
            acceleration = add(acceleration, mul(this.mInvMass[i], force));
        }

        const iP1 = i + 1;
        if (iP1 < this.mNumParticles) {
            diff = sub(position[iP1], position[i]);
            ratio = this.mLength[i] / vectorLength(diff);
            force = mul(this.mConstant[i] * (1 - ratio), diff);
            acceleration = add(acceleration, mul(this.mInvMass[i], force));
        }

        return acceleration;
    }
}
