// gtengine-js: TypeScript port of Geometric Tools Engine (GTE) SegmentMesh.h
// Upstream: David Eberly, Geometric Tools, Redmond WA 98052
// Copyright (c) 1998-2026 David Eberly
// Distributed under the Boost Software License, Version 1.0.
// https://www.boost.org/LICENSE_1_0.txt

// The 'vertices' are a vertex pool that contain the vertices of the mesh. The
// 'indices' are index pairs into 'vertices', each pair representing a segment
// of the polysegment. The indexed constructor does not require that all
// elements of the vertex pool participate in the polysegment. The polysegment
// segments are unrestricted. They can form an open or closed polysegment. They
// can intersect at interior points of the segments. A segment can be
// degenerate whereby its endpoints are equal.
//
// Port notes: see AlignedBox.ts for the shared geometric-primitive
// conventions. The three value constructors are disambiguated as the named
// static factories fromDisjoint, fromContiguous and fromIndexed; the default
// constructor is 'new SegmentMesh()' (it stores no vectors, so it needs no
// dimension). The nested enum 'Topology' is exported as
// 'SegmentMeshTopology' to keep the library's global export names unique and
// is also reachable as 'SegmentMesh.Topology'. 'std::array<size_t, 2>'
// becomes the tuple type [number, number].

import { logAssert } from './Logger.js';
import { Vector } from './Vector.js';

// The comments for topology are based on the input vertices having L >= 2
// elements ordered { V[0], V[1], ..., V[L-1] }.
export enum SegmentMeshTopology {
    // The default constructor has no information about the mesh topology.
    UNKNOWN = 0,

    // L must be an even number. The L/2 segments are
    // <V[0],V[1]>, <V[2],V[3]>, ..., <V[L-2],V[L-1]>.
    DISJOINT = 1,

    // The vertices form an open polyline. The L-1 segments are
    // <V[0],V[1]>, <V[1],V[2]>, ..., <V[L-2],V[L-1]>.
    CONTIGUOUS_OPEN = 2,

    // The vertices form a closed polyline. The L segments are
    // <V[0],V[1]>, ..., <V[L-2],V[L-1]>, <V[L-1],V[0]>.
    CONTIGUOUS_CLOSED = 3,

    // The segments are generated by indexing into the vertex array. The mesh
    // has M segments, each segment generated by an index pair S[i] for
    // 0 <= i <= M-1. The segments are <V[S[0][0],S[0][1]>,
    // <V[S[1][0],S[1][1]>, ..., <V[S[M-1][0],S[M-1][1]>. The other topologies
    // can be represented using the indexed approach,
    //   DISJOINT: S[i] = {2*i, 2*i+1} for 0 <= i <= (L-2)/2
    //   CONTIGUOUS_OPEN: S[i] = {i, i + 1} for 0 <= i <= L-2
    //   CONTIGUOUS_CLOSED: S[i] = {i, (i + 1) % L} for 0 <= i <= L-1
    INDEXED = 4
}

// Copies the vertex pool (C++ copies the std::vector by value) and verifies
// that the vertices all have the same dimension. Upstream gets the dimension
// check for free from the Vector<N, T> template parameter; the port has a
// runtime dimension, so the equivalent condition is checked here.
function copyVertices(vertices: readonly Vector[]): Vector[] {
    const copy: Vector[] = new Array<Vector>(vertices.length);
    for (let i = 0; i < vertices.length; ++i) {
        logAssert(vertices[i].size === vertices[0].size,
            'SegmentMesh: mismatched vertex dimensions.');
        copy[i] = vertices[i].clone();
    }
    return copy;
}

export class SegmentMesh {
    // The nested C++ enum, reachable through the class as upstream's
    // SegmentMesh<N, T>::Topology is.
    static readonly Topology = SegmentMeshTopology;

    private mTopology: SegmentMeshTopology;
    private mVertices: Vector[];
    private mIndices: [number, number][];

    // The port of the default constructor: no topology information, no
    // vertices and no indices.
    constructor() {
        this.mTopology = SegmentMeshTopology.UNKNOWN;
        this.mVertices = [];
        this.mIndices = [];
    }

    // Create a mesh with DISJOINT topology. NOTE: The upstream documentation
    // says L must be even, but the upstream constructor asserts only L >= 2
    // and then builds floor(L/2) segments. The quirk is preserved: an odd
    // vertex count silently leaves the last vertex unused.
    static fromDisjoint(vertices: readonly Vector[]): SegmentMesh {
        logAssert(vertices.length >= 2, 'Invalid number of vertices.');

        const mesh = new SegmentMesh();
        mesh.mTopology = SegmentMeshTopology.DISJOINT;
        mesh.mVertices = copyVertices(vertices);

        const numIndices = Math.floor(vertices.length / 2);
        mesh.mIndices = new Array<[number, number]>(numIndices);
        for (let i = 0; i < numIndices; ++i) {
            mesh.mIndices[i] = [2 * i, 2 * i + 1];
        }
        return mesh;
    }

    // Create a mesh with CONTIGUOUS topology. Set isOpen to 'true' for
    // CONTIGUOUS_OPEN topology or 'false' for CONTIGUOUS_CLOSED topology.
    static fromContiguous(vertices: readonly Vector[],
        isOpen: boolean): SegmentMesh {
        logAssert(vertices.length >= 2, 'Invalid number of vertices.');

        const mesh = new SegmentMesh();
        mesh.mVertices = copyVertices(vertices);

        if (isOpen) {
            mesh.mTopology = SegmentMeshTopology.CONTIGUOUS_OPEN;
            const numIndices = vertices.length - 1;
            mesh.mIndices = new Array<[number, number]>(numIndices);
            for (let i0 = 0, i1 = 1; i0 < numIndices; i0 = i1++) {
                mesh.mIndices[i0] = [i0, i1];
            }
        } else {
            // NOTE: The upstream documentation for CONTIGUOUS_CLOSED lists
            // S[i] = {i, (i+1) % L}, but the upstream loop stores
            // S[i1] = {i1-1, i1}, i.e. the same segment set rotated by one so
            // that the wrap-around segment <V[L-1],V[0]> is S[0]. The upstream
            // storage order is preserved here.
            mesh.mTopology = SegmentMeshTopology.CONTIGUOUS_CLOSED;
            const numIndices = vertices.length;
            mesh.mIndices = new Array<[number, number]>(numIndices);
            for (let i0 = numIndices - 1, i1 = 0; i1 < numIndices; i0 = i1++) {
                mesh.mIndices[i1] = [i0, i1];
            }
        }
        return mesh;
    }

    // Create a mesh with INDEXED topology. If the caller is certain that the
    // indices satisfy indices[i] < vertices.length for all i, set
    // validateIndices to 'false'. Otherwise, set validateIndices to 'true' so
    // that the indices are validated internally.
    static fromIndexed(vertices: readonly Vector[],
        indices: readonly [number, number][],
        validateIndices: boolean): SegmentMesh {
        logAssert(vertices.length >= 2 && indices.length >= 1,
            'Invalid number of vertices or indices.');

        const mesh = new SegmentMesh();
        mesh.mTopology = SegmentMeshTopology.INDEXED;
        mesh.mVertices = copyVertices(vertices);
        mesh.mIndices = indices.map((pair): [number, number] =>
            [pair[0], pair[1]]);

        if (validateIndices) {
            for (let i = 0; i < indices.length; ++i) {
                logAssert(
                    indices[i][0] < vertices.length
                    && indices[i][1] < vertices.length,
                    'Invalid index into vertex array.');
            }
        }
        return mesh;
    }

    // Member access. For now the vertices and indices are read-only.
    getTopology(): SegmentMeshTopology {
        return this.mTopology;
    }

    getVertices(): readonly Vector[] {
        return this.mVertices;
    }

    getIndices(): readonly [number, number][] {
        return this.mIndices;
    }

    // The dimension N of the vertices, or 0 when the mesh has no vertices.
    get dimension(): number {
        return this.mVertices.length > 0 ? this.mVertices[0].size : 0;
    }
}

// Aliases for convenience (the ports of the upstream template aliases).
export type SegmentMesh2 = SegmentMesh;
export type SegmentMesh3 = SegmentMesh;
